---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/latest/config-file/ and in linters documentation

DISABLE:
  - SPELL

FLAVOR_SUGGESTIONS: false
GITHUB_COMMENT_REPORTER: true
SECURITY_SUGGESTIONS: false
SHOW_ELAPSED_TIME: true
VALIDATE_ALL_CODEBASE: true

# TODO: Remove once actionlint supports $/ references (https://github.com/rhysd/actionlint/issues/711).
ACTION_ACTIONLINT_ARGUMENTS: >-
  -ignore '^reusable workflow call "\$/\.github/workflows/ci\.yml" at "uses" is not following the format'
ACTION_ZIZMOR_DISABLE_ERRORS: true # TODO: Remove this once the zizmor version is updated in MegaLinter.
ANSIBLE_ANSIBLE_LINT_CONFIG_FILE: .github/linters/.ansible-lint.yml
ANSIBLE_ANSIBLE_LINT_PRE_COMMANDS:
  - command: ansible-galaxy collection install --requirements-file ./ansible/requirements.yml
    cwd: "workspace"
    run_before_linters: true
MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: (^\.github/PULL_REQUEST_TEMPLATE\.md$)
YAML_YAMLLINT_ARGUMENTS: --strict
