---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/latest/config-file/ and in linters documentation

DISABLE:
  - SPELL

FLAVOR_SUGGESTIONS: false
GITHUB_COMMENT_REPORTER: true
SECURITY_SUGGESTIONS: false
SHOW_ELAPSED_TIME: true
VALIDATE_ALL_CODEBASE: true

ANSIBLE_ANSIBLE_LINT_CONFIG_FILE: .github/linters/.ansible-lint.yml
ANSIBLE_ANSIBLE_LINT_PRE_COMMANDS:
  - command: ansible-galaxy collection install --requirements-file ./ansible/requirements.yml
    cwd: "workspace"
    run_before_linters: true
MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: (^\.github/PULL_REQUEST_TEMPLATE\.md$)
# Disable: https://docs.kics.io/latest/queries/ansible-queries/c6473dae-8477-4119-88b7-b909b435ce7b/
REPOSITORY_KICS_ARGUMENTS: --exclude-queries c6473dae-8477-4119-88b7-b909b435ce7b
YAML_YAMLLINT_ARGUMENTS: --strict
