---
# Documentation:
#   - https://developer.1password.com/docs/cli/get-started/#step-1-install-1password-cli

# TODO: Maybe do the debsig-verify part as well?
- name: Install 1password cli dependencies
  ansible.builtin.apt:
    package:
      - python3-debian
    state: present

- name: Add 1password cli repository
  ansible.builtin.deb822_repository:
    name: 1password
    types: [deb]
    architectures: amd64
    uris: "https://downloads.1password.com/linux/debian/amd64"
    signed_by: "https://downloads.1password.com/linux/keys/1password.asc"
    suites: [stable]
    components: [main]
    state: present
    enabled: true

- name: Install 1password cli
  ansible.builtin.apt:
    package:
      - 1password-cli
    update_cache: true
    state: present

- name: Add 1password cli service token
  ansible.builtin.template:
    src: 1password_cli/1password.sh.j2
    dest: /etc/profile.d/1password.sh
    owner: root
    group: root
    mode: "0644"
  tags:
    - molecule-notest
