---
- name: VPS Setup
  hosts: all
  become: true
  gather_facts: true
  remote_user: root  # First time run as root
  # remote_user: ansible  # Later run as ansible
  vars:
    user_name: ansible
    user_password: "{{ lookup('env','VPS_PASSWORD') }}"
    # https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#how-do-i-generate-encrypted-passwords-for-the-user-module

  pre_tasks:
    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

  handlers:
    - name: Restart sshd
      ansible.builtin.service:
        name: ssh
        state: restarted

    - name: Restart unattended-upgrades
      ansible.builtin.service:
        name: unattended-upgrades
        state: restarted

  tasks:
    # User
    - name: Create system user group
      ansible.builtin.group:
        name: "{{ user_name }}"
        state: present

    - name: Create system user
      ansible.builtin.user:
        name: "{{ user_name }}"
        password: "{{ user_password }}"
        shell: /bin/bash
        groups:
          - "{{ user_name }}"
        createhome: true
        state: present

    - name: Add sudo privileges for user
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        regexp: "^{{ user_name }}"
        line: "{{ user_name }} ALL=(ALL) NOPASSWD:ALL"
        state: present
        validate: "visudo -cf %s"

    # SSH
    - name: Install SSH
      ansible.builtin.apt:
        package:
          - openssh-client
          - openssh-server
        state: present

    - name: SSH is started and enabled
      ansible.builtin.service:
        name: ssh
        state: started
        enabled: true

    - name: Create SSH directory
      ansible.builtin.file:
        path: "/home/{{ user_name }}/.ssh"
        state: directory
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: "0700"

    - name: Add authorized key for user
      ansible.builtin.copy:
        remote_src: true
        src: /root/.ssh/authorized_keys
        dest: /home/{{ user_name }}/.ssh/authorized_keys
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: "0600"
      tags:
        - molecule-notest  # Root user does not have authorized_keys in container.

    - name: Set SSH configuration
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
        validate: "sshd -t -f %s"
      loop:
        - regexp: "^#?PermitRootLogin"
          line: "PermitRootLogin no"

        - regexp: "^#?PasswordAuthentication"
          line: "PasswordAuthentication no"
      notify: Restart sshd

    # UFW
    - name: Install UFW
      ansible.builtin.apt:
        package:
          - ufw
        state: present

    - name: Deny incoming traffic
      community.general.ufw:
        default: deny
        direction: incoming
      tags:
        - molecule-notest

    - name: Allow outgoing traffic
      community.general.ufw:
        default: allow
        direction: outgoing
      tags:
        - molecule-notest

    - name: Allow specific ports
      community.general.ufw:
        rule: allow
        port: "{{ item }}"
      loop:
        - 22
        - 80
        - 443
      tags:
        - molecule-notest

    - name: Enable UFW
      community.general.ufw:
        state: enabled
      tags:
        - molecule-notest

    # Unattended upgrades
    - name: Install unattended-upgrades
      ansible.builtin.apt:
        package:
          - unattended-upgrades
        state: present

    - name: Unattended upgrades is started and enabled
      ansible.builtin.service:
        name: unattended-upgrades
        state: started
        enabled: true

    - name: Unattended upgrades 20auto-upgrades
      ansible.builtin.lineinfile:
        path: /etc/apt/apt.conf.d/20auto-upgrades
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      loop:
        - regexp: "^(\/\/)?APT::Periodic::Update-Package-Lists"
          line: "APT::Periodic::Update-Package-Lists \"1\";"

        - regexp: "^(\/\/)?APT::Periodic::Unattended-Upgrade"
          line: "APT::Periodic::Unattended-Upgrade \"1\";"
      notify: Restart unattended-upgrades

    - name: Unattended upgrades 50unattended-upgrades
      ansible.builtin.lineinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      loop:
        - regexp: "^(\/\/)?Unattended-Upgrade::Remove-Unused-Dependencies "
          line: "Unattended-Upgrade::Remove-Unused-Dependencies \"true\";"

        - regexp: "^(\/\/)?Unattended-Upgrade::Automatic-Reboot "
          line: "Unattended-Upgrade::Automatic-Reboot \"true\";"

        - regexp: "^(\/\/)?Unattended-Upgrade::Automatic-Reboot-Time "
          line: "Unattended-Upgrade::Automatic-Reboot-Time \"04:00\";"
      notify: Restart unattended-upgrades

    # Fail2ban
    - name: Install fail2ban
      ansible.builtin.apt:
        package:
          - fail2ban
        state: present

    - name: Fail2ban is started and enabled
      ansible.builtin.service:
        name: fail2ban
        state: started
        enabled: true

    # 1Password CLI
    # TODO: Maybe do the debsig-verify part as well?
    # https://developer.1password.com/docs/cli/get-started/#step-1-install-1password-cli
    - name: Install 1Password CLI dependencies
      ansible.builtin.apt:
        package:
          - python3-debian
        state: present

    - name: Add 1Password CLI repository
      ansible.builtin.deb822_repository:
        name: 1password
        types: [deb]
        architectures: amd64
        uris: "https://downloads.1password.com/linux/debian/amd64"
        signed_by: "https://downloads.1password.com/linux/keys/1password.asc"
        suites: [stable]
        components: [main]
        state: present
        enabled: true

    - name: Install 1Password CLI
      ansible.builtin.apt:
        package:
          - 1password-cli
        update_cache: true
        state: present

    - name: Add 1Password CLI service token
      ansible.builtin.template:
        src: 1password/1password.sh.j2
        dest: /etc/profile.d/1password.sh
        owner: root
        group: root
        mode: "0644"
      tags:
        - molecule-notest

    # System packages
    - name: Install system packages
      ansible.builtin.apt:
        package:
          - build-essential
          - curl
          - nmap
          - python3-kubernetes
          - python3-pip
          - python3-virtualenv
          - tmux
          - tree
          - zip
        state: present

    - name: Update system packages to the latest version
      ansible.builtin.apt:
        upgrade: safe
