---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 12 * * 6" # Every Saturday at 12:00

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prek:
    permissions:
      contents: read
    uses: daniel-mizsak/workflows/.github/workflows/prek.yml@31499185a34723e78c51d951b98941c07e139780 # v2.3.0

  lint:
    permissions:
      contents: read
      pull-requests: write
    uses: daniel-mizsak/workflows/.github/workflows/lint.yml@31499185a34723e78c51d951b98941c07e139780 # v2.3.0
    with:
      megalinter-config: "./.github/linters/.megalinter.yml"

  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out the codebase
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Install just
        uses: daniel-mizsak/workflows/.github/actions/setup-just@31499185a34723e78c51d951b98941c07e139780 # v2.3.0

      - name: Run quality checks with just
        run: |
          just install
          just check-all
